<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'GravityKit\\BlockMCP\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'GravityKit\\BlockMCP\\Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'GravityKit\\BlockMCP\\Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\TrustedLogin\\' => array($vendorDir . '/trustedlogin/client/src'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Illuminate\\Validation\\' => array($vendorDir . '/illuminate/validation'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Illuminate\\Translation\\' => array($vendorDir . '/illuminate/translation'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Illuminate\\Support\\' => array($vendorDir . '/illuminate/support'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Illuminate\\Filesystem\\' => array($vendorDir . '/illuminate/filesystem'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
    'GravityKit\\BlockMCP\\Foundation\\ThirdParty\\Illuminate\\Container\\' => array($vendorDir . '/illuminate/container'),
    'GravityKit\\BlockMCP\\Foundation\\' => array($vendorDir . '/gravitykit/foundation/src'),
);
